language: python
python:
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
service: mysql
install:
  - pip install -r requirements.txt
  - pip install Django==$DJANGO_VERSION
  - pip install eth-testrpc
before_script:
  - mysql -u root -e "CREATE DATABASE travis_ci CHARACTER SET utf8mb4"
script:
  - testrpc-py &
  - python manage.py test
