language: python
python:
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
install:
  - pip install -r requirements.txt
  - pip install Django==$DJANGO_VERSION
script:
  - python -Wall manage.py test
